# fly.toml app configuration file generated for worlds-predictions on 2023-10-09T02:27:46+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "worlds-predictions"
primary_region = "waw"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
